name: ⏳ Sync upstream Releases

# 定时每天同步，也可监听仓库 dispatch
on:
  schedule:
    - cron: '0 2 * * *'     # 每天 UTC 2:00（北京时间 10:00）执行
  workflow_dispatch:        # 可手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout with full history
        uses: actions/checkout@v3
        with:
          fetch-depth: 0       # 拉取所有提交和标签

      - name: Add upstream remote
        run: |
          git remote add upstream https://github.com/homuler/MediaPipeUnityPlugin.git
          git fetch upstream --tags

      - name: Push tags to origin
        # 使用默认的 GITHUB_TOKEN 即可推送标签
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
        run: |
          git push origin --tags
