name: ⏳ Sync upstream Releases

# 定时每天同步，也可监听仓库 dispatch
on:
  schedule:
    - cron: '0 2 * * *'     # 每天 UTC 2:00（北京时间 10:00）执行
  workflow_dispatch:        # 可手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout with full history
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.WORKFLOW_TOKEN }}     # ← 关键：用你新建的 PAT 来克隆并给后续 push 授权

      - name: Add upstream remote
        run: |
          git remote add upstream https://github.com/homuler/MediaPipeUnityPlugin.git
          git fetch upstream --tags

      - name: Push tags to origin
        run: git push origin --tags
        # 不再需要单独在这里声明 env，因为 checkout 已经用 PAT 设置好了凭据

