name: ⏳ Sync upstream Releases
on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout with full history and PAT
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.WORKFLOW_TOKEN }}    # ← 这里用你的 Classic PAT

      - name: Add upstream remote
        run: |
          git remote add upstream https://github.com/homuler/MediaPipeUnityPlugin.git
          git fetch upstream --tags

      - name: Push tags to origin
        run: git push origin --tags            # ← 这时就会走上面注入的 PAT
